# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: ".*\\.ipynb$"
-   repo: local
    hooks:
    -   id: clean_cell_nums
        name: clean_cell_nums
        entry: bash
        args:
            - -c  # run in sequence
            - "python clean_cell_nums.py"
        language: system
        pass_filenames: false
    -   id: clean
        name: clean
        entry: bash
        args:
            - -c  # run in sequence
            - "black . && flake8 && isort ."
        language: system
        pass_filenames: false
